### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: Class 'com_amap_api_location_AMapLocationClient' has no instance getter 'tag'.

### ISSUE THREAD

**Issue by lvyandev** [fluttify-project/amap_search_fluttify#27]
**插件版本**
```amap_search_fluttify: ^0.8.0+b2681d9```
**遇到bug的平台(Android/iOS)**
安卓
**描述bug**
AmapSearch.dispose方法报错
**复现步骤**
关闭定位搜索页面以后出现
**期望行为**

**截图**
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class 'com_amap_api_location_AMapLocationClient' has no instance getter 'tag'.
    Receiver: Instance of 'com_amap_api_location_AMapLocationClient'
    Tried calling: tag
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      AmapSearch.dispose.<anonymous closure> (package:amap_search_fluttify/src/facade/amap_search.dart:1016:40)
    #2      WhereIterator.moveNext (dart:_internal/iterable.dart:442:11)
    #3      MappedIterator.moveNext (dart:_internal/iterable.dart:394:19)
    #4      new List.from (dart:core-patch/array_patch.dart:47:19)
    #5      Iterable.toList (dart:core/iterable.dart:400:5)
    #6      Ref_Batch.release_batch (package:foundation_fluttify/src/type/core/ref.dart:88:43)
    #7      AmapSearch.dispose (package:amap_search_fluttify/src/facade/amap_search.dart:1017:52)
    #8      AmapSearchDisposeMixin.dispose (package:amap_search_fluttify/src/facade/amap_search.dart:14:16)
    #9      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
    #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
    #11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
    #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
    #16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
    #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
    #22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
    #25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #27     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534:16)
    #28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
    #31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #33     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
    #34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
    #37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744:13)
    #38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
    #39     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
    #40     _InactiveElements._unmount (packag
```
**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] Connected device (1 available)

```

**Comment by yohom** [comment]
`flutter packages upgrade; flutter packages get`跑一下。

**Comment by lvyandev** [comment]
这边尝试了以后还是会有这个报错呀

**Comment by yohom** [comment]
看一下你的pubspec.locl里foundation_fluttify的版本

**Comment by lvyandev** [comment]
```
foundation_fluttify:
    dependency: transitive
    description:
      name: foundation_fluttify
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.5.0"
```
不好意思，回复晚了
