### ISSUE TITLE
逆地理编码报异常

### ISSUE THREAD

**Issue by ligui-iOS** [fluttify-project/amap_search_fluttify#30]
**插件版本**
0.8.2+1
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
E/flutter (24140): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (24140): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (24140): <asynchronous suspension>
E/flutter (24140): #2      com_amap_api_services_geocoder_RegeocodeResult.getRegeocodeAddress (package:amap_search_fluttify/src/android/com/amap/api/services/geocoder/RegeocodeResult.g.dart:104:77)
E/flutter (24140): #3      _AndroidSearchListener.onRegeocodeSearched (package:amap_search_fluttify/src/facade/amap_search.dart:1096:31)
E/flutter (24140): #4      com_amap_api_services_geocoder_GeocodeSearch.setOnGeocodeSearchListener.<anonymous closure> (package:amap_search_fluttify/src/android/com/amap/api/services/geocoder/GeocodeSearch.g.dart:123:21)
E/flutter (24140): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter (24140): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter (24140): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter (24140): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter (24140): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (24140): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (24140): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (24140): #12     _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter (24140): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
**复现步骤**

**期望行为**

**截图**

**flutter doctor**
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.4 18E226,
    locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)

**Comment by ligui-iOS** [comment]
refId不知道为什么为null了

**Comment by ligui-iOS** [comment]
com.amap.api.services.poisearch.PoiResult@null::getPois([])
